# Generated by Django 4.1 on 2023-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagarismapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='topic',
            field=models.CharField(default='chap1', max_length=100),
        ),
    ]
