# Generated by Django 4.1 on 2023-03-10 15:11

from django.db import migrations, models
import django.db.models.deletion
import plagarismapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('plagarismapi', '0002_documents_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='docname',
            field=models.FileField(upload_to=plagarismapi.models.get_upload_path),
        ),
        migrations.CreateModel(
            name='pdfdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plagarismapi.studetails')),
            ],
        ),
    ]
